Added support for a boot delay

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -26,6 +26,21 @@ export JAVA_MEM_ARGS
 # Update the SSL stuff
 /update-ssl
 
+MAX_BOOT_DELAY="60"
+if [ -v BOOT_DELAY ] && [[ "${BOOT_DELAY}" =~ ^[0-9]+$ ]] ; then
+	BOOT_DELAY="$(( 10#${BOOT_DELAY} ))"
+	if [ ${BOOT_DELAY} -gt 0 ] ; then
+		[ ${BOOT_DELAY} -gt ${MAX_BOOT_DELAY} ] && BOOT_DELAY=${MAX_BOOT_DELAY}
+		say "Applying a boot delay of ${BOOT_DELAY} seconds"
+		START="$(date +%s)"
+		while true ; do
+			DIFF="$(( $(date +%s) - START ))"
+			[ ${DIFF} -ge ${BOOT_DELAY} ] && break
+			sleep 1 || fail "Boot delay aborted - exiting"
+		done
+	fi
+fi
+
 [ -e "${CONF_DIR}" ] || fail "The data directory [${CONF_DIR}] does not exist"
 [ -d "${CONF_DIR}" ] || fail "The path [${CONF_DIR}] is not a directory"
 [ -r "${CONF_DIR}" ] || fail "The data directory [${CONF_DIR}] is not readable by ${USER} (${UID}:$(id -g))"
